name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies with uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run linter
        run: |
          source .venv/bin/activate
          ruff check gendiff tests

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -vv --color=yes --exitfirst tests
