name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .[dev]
          uv pip install pytest-cov

      - name: Run linter
        run: |
          source .venv/bin/activate
          ruff check gendiff tests

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=gendiff --cov-report=xml -vv --color=yes --exitfirst tests

        - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sroonla
            -Dsonar.projectKey=sroonla_python-project-50
            -Dsonar.projectName=python-project-50
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.language=py
            -Dsonar.python.version=3.13
